[package]
name = "todoist-rest-api"
description = "A Todoist REST API wrapper for Rust"
version = "1.0.0"
edition = "2021"
authors = ["dkim19375"]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }#, optional = true }
chrono-tz = { version = "0.8.3", features = ["serde"] }#, optional = true }
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
uuid = "1.4.1"

[features]
#chrono = ["dep:chrono", "dep:chrono-tz"]