name: Check rust code formatting

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List
        run: ls -a
      - name: Set cargo fmt output
        run: export FMT_OUTPUT=$(cargo fmt --message-format short)
      - name: Print cargo fmt output
        run: echo $FMT_OUTPUT
      - name: Check cargo fmt output
        run: if [ -z "$(echo "$FMT_OUTPUT"|tr -d '\n')" ]; then exit 1; fi